---
language: go

stages:
  - lint
  - build
  # - deploy

go:
  - 1.13.1


jobs:
  include:
    - name: lint
      stage: lint
      os: linux
      before_install:
        - go get -u golang.org/x/lint/golint
      script:
        - make ci-lint

    - name: macOS build
      stage: build
      os: osx
      script:
        - make build
        - ./bin/gocast version

    - name: linux build
      stage: build
      os: linux
      script:
        - make build
        - ./bin/gocast version

    - name: windows build
      stage: build
      os: windows
      before_install:
        - choco install make
      script:
        - make build
        - dir
        - dir bin

    # - stage: deploy
    #   name: "Deployment"
    #   if: tag IS present
    #   script: make release
    #   deploy:
    #     provider: releases
    #     overwrite: true
    #     file:
    #       - a
    #       - b
    #       - c
    #     skip_cleanup: true
    #     on:
    #       repo: derphilipp/gocast
    #       tags: true
